"""Train the lossy-mode rANS tables and emit them as the hardware ROM.

  python scripts/gen_lossy_rom.py               # challenge data (data/raw)
  python scripts/gen_lossy_rom.py --synthetic   # no dataset needed

Writes model/nlc/lossy_tables.json (read by nlc.lossy.default_tables, i.e. the
decoder) and src/nlc_lossy_rom.v (module nlc_lossy_rom, used by nlc_rans.sv).
The two must always be regenerated together.
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "model"))

from nlc.data import load_challenge, synthetic  # noqa: E402
from nlc.lossy import TABLES_PATH, LossyConfig, train_tables  # noqa: E402


def rom_verilog(cdfs: list[list[int]], cfg: LossyConfig, src: str) -> str:
    """The text of src/nlc_lossy_rom.v for these tables (also used by the change-guard tests)."""
    sym_w = (cfg.n_sym - 1).bit_length()
    ctx_w = max(1, (cfg.n_ctx - 1).bit_length())
    pb = cfg.prob_bits
    aw = ctx_w + sym_w
    lines = [
        "// GENERATED by scripts/gen_lossy_rom.py -- do not edit.",
        f"// Static rANS tables for the lossy mode, trained on {src}.",
        f"// fc = {{f_s[{pb}:0], c_s[{pb - 1}:0]}} for addr = {{ctx, sym}}; every table sums to 2^{pb}.",
        "`default_nettype none",
        "",
        "module nlc_lossy_rom (",
        f"    input  wire [{aw - 1}:0] addr,",
        f"    output reg  [{2 * pb}:0] fc",
        ");",
        "  always @(*) begin",
        "    case (addr)",
    ]
    for k, cdf in enumerate(cdfs):
        for s in range(cfg.n_sym):
            f, c = cdf[s + 1] - cdf[s], cdf[s]
            lines.append(f"      {aw}'d{(k << sym_w) | s}: fc = {{{pb + 1}'d{f}, {pb}'d{c}}};")
    lines += ["      default: fc = 0;", "    endcase", "  end", "endmodule", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default=str(ROOT / "data" / "raw"))
    ap.add_argument("--synthetic", action="store_true")
    ap.add_argument("--channels", type=int, default=32)
    ap.add_argument("--seconds", type=float, default=2.0)
    args = ap.parse_args()

    cfg = LossyConfig()
    if args.synthetic:
        fs, x = 19531, synthetic(args.channels, int(args.seconds * 19531), seed=7)
        src = "synthetic"
    else:
        fs, x = load_challenge(args.data, args.channels)
        x = x[: int(args.seconds * fs)]
        src = f"{args.channels} challenge files, first {args.seconds} s"
    cdfs = train_tables(x, cfg)

    TABLES_PATH.write_text(json.dumps({"source": src, "cdfs": cdfs}) + "\n")
    (ROOT / "src" / "nlc_lossy_rom.v").write_text(rom_verilog(cdfs, cfg, src))
    print(f"tables from {src} -> {TABLES_PATH.relative_to(ROOT)}, src/nlc_lossy_rom.v")


if __name__ == "__main__":
    main()
